package com.paw.pawganizr.contact;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel
public class ContactDto {

    @ApiModelProperty(notes = "Id generated by the database")
    private Long id;

    @ApiModelProperty(notes = "Type of the contact", example = "VET", required = true)
    private ContactType type;

    @ApiModelProperty(notes = "Description", example = "Surgeon from our pet clinic")
    private String description;

    @ApiModelProperty(notes = "Contact's name", example = "Jane Doe", required = true)
    private String name;

    @ApiModelProperty(notes = "Phone number", example = "666 666 666", required = true)
    private String phoneNumber;

    @ApiModelProperty(notes = "Email address", example = "jane@petclinic.com")
    private String email;
}
