package com.paw.pawganizr.pet;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PetDto {
    @ApiModelProperty(notes = "Id generated by the database")
    private Long id;

    @ApiModelProperty(example = "Maple", required = true)
    private String petName;

    @ApiModelProperty(example = "CAT", required = true)
    private PetType type;

    @ApiModelProperty(example = "FEMALE")
    private PetGender gender;

    @ApiModelProperty(example = "234567890654537")
    private String chipNumber;

    @ApiModelProperty(example = "mysweetcatswebpage.com/photos/1")
    private String petAvatarUrl;

    @ApiModelProperty(example = "Brown")
    private String color;

    @ApiModelProperty(example = "2007-03-12")
    private LocalDate birthDate;

    @ApiModelProperty(example = "TRUE")
    private boolean dead;

    @ApiModelProperty(example = "2020-02-14")
    private LocalDate deathDate;

    @ApiModelProperty(example = "British shorthair")
    private String race;
}
