package com.paw.pawganizr.treatment;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class TreatmentDto {
    @ApiModelProperty(notes = "Id generated by the database")
    private Long id;

    @ApiModelProperty(example = "VACCINATION", required = true)
    private TreatmentType type;

    @ApiModelProperty(example = "Rabies vaccine")
    private String description;

    @ApiModelProperty(example = "2019-09-01", required = true)
    private LocalDate treatmentStartDate;

    @ApiModelProperty(example = "2019-09-01")
    private LocalDate treatmentEndDate;
}
